stages:
  prepare_data:
    cmd: python "/app/src/prepare_data.py"
    deps:
      - "/app/data/raw/train_latest.csv"
      - "/app/src/prepare_data.py"
    outs:
      - "/app/data/processed/X_train.csv"
      - "/app/data/processed/X_test.csv"
      - "/app/data/processed/y_train.csv"
      - "/app/data/processed/y_test.csv"
      - "/app/model/encoder.joblib"
      - "/app/model/label_encoder.joblib"
      - "/app/model/scaler.joblib"

  train_model:
    cmd: python "/app/src/train_model.py"
    deps:
      - "/app/data/processed/X_train.csv"
      - "/app/data/processed/X_test.csv"
      - "/app/data/processed/y_train.csv"
      - "/app/data/processed/y_test.csv"
      - "/app/src/train_model.py"
      - "/app/src/best_f1_score.txt"
    outs:
      - "/app/model/XGBoost_model.joblib"